# Lesson 4.3: Pandas Fundamentals

**Analyst:** Meron Welderufael
**Date:** 10/26/2026
**Client:** FinFlow (Product Analytics engagement led by Hannah Whitford)
**Notebook purpose:** Load the FinFlow synthetic dataset into Pandas, run
the standard inspection routine, and practice basic DataFrame creation
and saving.

This notebook is the second day of the FinFlow Customer Churn Investigation.
The 1,000-row CSV loaded here is the same dataset generated in Lesson 4.2.
By Friday it will be replaced with a 200,000-row version for the full project.

In [1]:
# Imports
import pandas as pd
import numpy as np

# Display all DataFrame columns when printing (Pandas truncates by default)
pd.set_option('display.max_columns', None)

# Show numbers with two decimal places where appropriate
pd.set_option('display.float_format', '{:.2f}'.format)

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.2
NumPy version: 2.4.4

## Loading the FinFlow synthetic dataset

In [2]:
df = pd.read_csv('finflow-customers-1000.csv')
print(f'Loaded {len(df)} rows from finflow-customers-1000.csv')

Loaded 1000 rows from finflow-customers-1000.csv

## Inspection routine

The first 40 seconds with any DataFrame. Confirm shape, types, value
ranges, and missing-data profile before asking any analytical question.

In [3]:
# Shape: how many rows and columns?
print(df.shape)

# Column names
print("Columns:")
for col in df.columns:
    print(f"{col}")

# Data types per column
print(df.dtypes)

# First five rows
df.head()

# Last five rows
df.tail()

# Full info dump
df.info()

(1000, 16)
Columns:
customer_id
first_name
last_name
email
city
state
country
signup_date
plan_tier
monthly_fee
last_login_date
total_sessions
avg_session_duration_minutes
support_tickets_opened
active
churn_date
customer_id                         str
first_name                          str
last_name                           str
email                               str
city                                str
state                               str
country                             str
signup_date                         str
plan_tier                           str
monthly_fee                     float64
last_login_date                     str
total_sessions                    int64
avg_session_duration_minutes    float64
support_tickets_opened            int64
active                             bool
churn_date                      float64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   1000 non-null   str
 1   first_name                    1000 non-null   str
 2   last_name                     1000 non-null   str
 3   email                         1000 non-null   str
 4   city                          1000 non-null   str
 5   state                         1000 non-null   str
 6   country                       1000 non-null   str
 7   signup_date                   1000 non-null   str
 8   plan_tier                     1000 non-null   str
 9   monthly_fee                   1000 non-null   float64
 10  last_login_date               1000 non-null   str
 11  total_sessions                1000 non-null   int64
 12  avg_session_duration_minutes  1000 non-null   float64
 13  support_tickets_opened        1000 non-null   int64
 14  active                        1000 non-null   bool
 15  churn_date                    0 non-null      float64
dtypes: bool(1), float64(3), int64(2), str(10)
memory usage: 118.3 KB

In [4]:
# Numeric summary statistics
df.describe()

,monthly_fee,total_sessions,avg_session_duration_minutes,support_tickets_opened,churn_date
count,1000.00,1000.00,1000.00,1000.00,0.00
mean,32.06,177.49,8.07,2.40,NaN
std,52.00,123.43,3.84,1.84,NaN
min,9.99,1.00,1.00,0.00,NaN
25%,9.99,50.00,4.80,1.00,NaN
50%,9.99,172.00,7.70,2.00,NaN
75%,29.99,291.25,11.40,4.00,NaN
max,199.00,400.00,15.00,8.00,NaN

**Observation:** Shape is correct (1000 x 16). Date columns are strings,
not datetimes, and will need parsing for time-series work. churn_date has
203 non-null values, matching the ~20% churn design. Monetary and engagement
columns all show sensible ranges. Ready to proceed.

## Re-loading with proper date parsing

`pd.read_csv` accepts a `parse_dates` parameter that converts named columns
from string to datetime during load. Always do this for date columns; many
Pandas operations work differently (and better) on real datetimes.

In [5]:
df = pd.read_csv('finflow-customers-1000.csv',
                parse_dates=['signup_date', 'last_login_date', 'churn_date'])
print(df.dtypes[['signup_date', 'last_login_date', 'churn_date']])

signup_date        datetime64[us]
last_login_date    datetime64[us]
churn_date          datetime64[s]
dtype: object

## Building a DataFrame from scratch

For test data, reference tables, and ad-hoc lookups, you often build a
small DataFrame inline rather than loading one from a file.

In [6]:
# A small reference table of FinFlow's plan pricing
plans = pd.DataFrame({
    'plan_tier': ['Basic','Pro','Enterprise'],
    'monthly_fee': [9.99, 29.99, 199.99],
    'annual_value': [9.99 *12, 29.99 *12, 199.99*12]
})
plans

    plan_tier  monthly_fee  annual_value
0       Basic         9.99        119.88
1         Pro        29.99        359.88
2  Enterprise       199.99       2399.88

## Saving a DataFrame to CSV

The plans table we just built doesn't exist as a file anywhere. Save it
so we can load it again later if needed.

In [7]:
plans.to_csv('finflow-plans.csv',index=False)
print("saved finflow-plans.csv")

saved finflow-plans.csv

In [8]:
plans_check = pd.read_csv('finflow-plans.csv')
plans_check

    plan_tier  monthly_fee  annual_value
0       Basic         9.99        119.88
1         Pro        29.99        359.88
2  Enterprise       199.99       2399.88